"""The single persistence boundary required by the farm use cases."""

from datetime import date
from typing import Protocol
from uuid import UUID

from crop_twin.domain.farm.models import ManagementEvent, Page, Plot, Season


class FarmRepository(Protocol):
    """Transaction-scoped farm access; implementations own queries and row locks."""

    def get_plot(self, plot_id: UUID, *, lock: bool = False) -> Plot | None: ...
    def add_plot(self, plot: Plot) -> None: ...
    def list_plots(self, limit: int, offset: int) -> Page[Plot]: ...
    def get_season(self, season_id: UUID, *, lock: bool = False) -> Season | None: ...
    def add_season(self, season: Season) -> None: ...
    def close_season(self, season_id: UUID, end_date: date) -> None: ...
    def seasons_for_plot(self, plot_id: UUID) -> list[Season]: ...
    def list_seasons(self, plot_id: UUID, limit: int, offset: int) -> Page[Season]: ...
    def get_event(self, event_id: UUID) -> ManagementEvent | None: ...
    def add_event(self, event: ManagementEvent) -> None: ...
    def has_current_event_after(self, season_id: UUID, end_date: date) -> bool: ...
    def list_events(
        self, season_id: UUID, limit: int, offset: int, *, include_history: bool = False
    ) -> Page[ManagementEvent]: ...
