"""The actual storage and password boundaries needed by account use cases."""

from datetime import datetime
from typing import Protocol
from uuid import UUID

from crop_twin.domain.identity.models import AuditEvent, Organization, Session, User
from crop_twin.domain.pagination import Page


class PasswordHasher(Protocol):
    """A mature password implementation; the application does not implement cryptography."""

    def hash(self, password: str) -> str: ...
    def verify(self, password_hash: str | None, password: str) -> bool: ...
    def needs_rehash(self, password_hash: str) -> bool: ...


class IdentityRepository(Protocol):
    """Identity persistence within one transaction; lock semantics belong to the adapter."""

    def add_organization(self, organization: Organization) -> None: ...
    def get_organization(self, organization_id: UUID) -> Organization | None: ...
    def get_user(self, user_id: UUID, *, lock: bool = False) -> User | None: ...
    def find_user(self, username: str, *, lock: bool = False) -> User | None: ...
    def add_user(self, user: User) -> None: ...
    def list_users(self, organization_id: UUID, limit: int, offset: int) -> Page[User]: ...
    def set_password(self, user_id: UUID, password_hash: str) -> None: ...
    def set_active(self, user_id: UUID, is_active: bool) -> None: ...
    def add_session(self, session: Session) -> None: ...
    def find_session(self, token_digest: str) -> Session | None: ...
    def remove_session(self, session_id: UUID) -> None: ...
    def revoke_sessions(self, user_id: UUID) -> None: ...
    def remove_expired_sessions(self, now: datetime) -> None: ...
    def lock_login_limit(self, source_key: str, now: datetime) -> tuple[int, datetime]: ...
    def set_login_failures(
        self, source_key: str, failures: int, window_start: datetime
    ) -> None: ...
    def add_audit(self, event: AuditEvent) -> None: ...
    def list_audits(self, organization_id: UUID, limit: int, offset: int) -> Page[AuditEvent]: ...
    def count_legacy_plots(self) -> int: ...
    def adopt_legacy_plots(self, organization_id: UUID) -> int: ...
