"""One storage boundary for the cohesive input module, shared by SQLite/PostgreSQL."""

from typing import Protocol
from uuid import UUID

from crop_twin.domain.pagination import Page
from crop_twin.domain.simulation.models import AssetKind, InputAsset, SimulationInput


class InputRepository(Protocol):
    """The caller supplies the organization and audit actor in the shared transaction."""

    def add_asset(self, asset: InputAsset) -> None: ...
    def get_asset(self, asset_id: UUID) -> InputAsset | None: ...
    def list_assets(
        self, kind: AssetKind, plot_id: UUID | None, limit: int, offset: int
    ) -> Page[InputAsset]: ...
    def next_version(self, season_id: UUID) -> int: ...
    def add_snapshot(self, snapshot: SimulationInput) -> None: ...
    def get_snapshot(self, input_id: UUID) -> SimulationInput | None: ...
    def list_snapshots(self, season_id: UUID, limit: int, offset: int) -> Page[SimulationInput]: ...
